version: '3.8'
services:
  gateway:
    build: ./backend/gateway
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=your_jwt_secret
      - DATABASE_URL=postgres://user:password@postgres:5432/userdb
    depends_on:
      - postgres
      - question-service
      - notification-service

  notification-service:
    build: ./backend/notification-service
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  question-service:
    build: ./backend/question-service
    environment:
      - MONGO_URL=mongodb://mongo:27017/questions
      - GPT_API_KEY=your_gpt_api_key
    depends_on:
      - mongo

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  mongo-data:
  postgres-data:
