openapi: 3.0.0
info:
  title: Answer API
  version: 1.0.0
  description: API documentation for managing answers

tags:
  - name: Answers
    description: Operations related to answers

paths:
  /api/answers/{id}:
    get:
      summary: Retrieve a specific answer by its ID
      tags:
        - Answers
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The answer ID
      responses:
        200:
          description: Answer found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: The answer ID
                    example: 63a3e2c9dcb8a5d6f9c5b1e2
                  questionId:
                    type: string
                    description: The related question ID
                    example: 63a3e2c9dcb8a5d6f9c5b1e1
                  answerText:
                    type: string
                    description: The content of the answer
                    example: "ISR은 Kafka에서 리더와 동기화된 파티션 집합입니다."
                  followUpQuestions:
                    type: array
                    description: List of follow-up questions
                    items:
                      type: string
                    example:
                      - "ISR 내의 팔로워가 리더로 승격되기 위한 조건은?"
                      - "Kafka에서 ISR 크기가 작아지면 시스템에 어떤 영향을 미칠까요?"
                  createdAt:
                    type: string
                    format: date-time
                    description: When the answer was created
                    example: "2024-12-27T16:00:00.000Z"
        404:
          description: Answer not found
        500:
          description: Server error

  /api/answers/question/{questionId}:
    get:
      summary: Retrieve an answer by question ID or generate one using GPT API
      tags:
        - Answers
      parameters:
        - in: path
          name: questionId
          required: true
          schema:
            type: string
          description: The question ID to find or generate an answer for
      responses:
        200:
          description: Answer found or generated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: The answer ID
                    example: 63a3e2c9dcb8a5d6f9c5b1e2
                  questionId:
                    type: string
                    description: The related question ID
                    example: 63a3e2c9dcb8a5d6f9c5b1e1
                  answerText:
                    type: string
                    description: The content of the answer
                    example: "ISR은 Kafka에서 리더와 동기화된 파티션 집합입니다."
                  followUpQuestions:
                    type: array
                    description: List of follow-up questions generated by GPT
                    items:
                      type: string
                    example:
                      - "ISR 내의 팔로워가 리더로 승격되기 위한 조건은?"
                      - "Kafka에서 ISR 크기가 작아지면 시스템에 어떤 영향을 미칠까요?"
                  isAppProvided:
                    type: boolean
                    description: Indicates if the answer was generated by GPT API
                    example: true
                  createdAt:
                    type: string
                    format: date-time
                    description: When the answer was created
                    example: "2024-12-27T16:00:00.000Z"
        404:
          description: Question not found
        500:
          description: Server error

  /api/answers:
    get:
      summary: Retrieve all answers
      tags: 
        - Answers
      responses:
        200:
          description: A list of answers
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      description: The answer ID
                      example: 61234abcd5678ef123456789
                    questionId:
                      type: string
                      description: The ID of the related question
                      example: 61234abcd5678ef123456789
                    answerText:
                      type: string
                      description: The content of the answer
                      example: "This is an answer."
                    isAppProvided:
                      type: boolean
                      description: Whether the answer is provided by the app
                      example: false
                    createdAt:
                      type: string
                      format: date-time
                      description: When the answer was created
                      example: "2024-12-26T15:30:00.000Z"

    post:
      summary: Create a new answer
      tags:
        - Answers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                questionId:
                  type: string
                  description: The ID of the related question
                  example: 61234abcd5678ef123456789
                answerText:
                  type: string
                  description: The content of the answer
                  example: "This is an answer."
                isAppProvided:
                  type: boolean
                  description: Whether the answer is provided by the app
                  example: false
      responses:
        201:
          description: Answer created successfully
        400:
          description: Invalid input data
    put:
      summary: Update an answer
      tags:
        - Answers
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The answer ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                answerText:
                  type: string
                  description: Updated answer text
                  example: "This is an updated answer."
                isAppProvided:
                  type: boolean
                  description: Whether the updated answer is app-provided
                  example: true
      responses:
        200:
          description: Answer updated successfully
        404:
          description: Answer not found

    delete:
      summary: Delete an answer
      tags:
        - Answers
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The answer ID
      responses:
        200:
          description: Answer deleted successfully
        404:
          description: Answer not found
